# docker run -p 80:80 -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx \ nginx-debug -g 'daemon off;'
services:
  web: 
    command: 
      - "nginx-debug" 
      - "-g" 
      - "daemon-off;"
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"